### ISSUE TITLE
Can you give a demo-blog repo?

### ISSUE THREAD

**Issue by luckypoem** [RyanZim/onessg#15]
thus it's more convenient for users

**Comment by RyanZim** [comment]
@luckypoem I agree there should be a demo repo; just haven't made one yet. Is there something you're not understanding? I would be glad to personally answer your questions.

I am currently refactoring the docs at: https://github.com/RyanZim/onessg/tree/docs, you may want to look at that branch. Feedback welcome!

---

Regarding Blogs: onessg is not "blog-aware" at present; although you could build a blog with it. I have never tried, I don't have a blog. I'm not opposed to making it a little bit more blog-friendly, however, I don't want it to become blog-centric. A few things to keep in mind:

- There is no way to automatically generate a Table of Contents, RSS Feed, etc.
- onessg doesn't alter your directory structure, so if you want URLs like: `http://mysite.com/2016/10/17/hello-world.html`, you will have to create that directory structure yourself. (I've considered adding URL manipulation capabilities, but never have.)

Despite these, building a blog with onessg should be possible.

---

FWIW, I'm a freelance web designer/developer (http://ryanzim.com), and I wanted to just write the content of my pages in HTML, and have a tool automatically wrap them with my layout/boilerplate (Copy/Pasting isn't DRY). All the existing SSGs either were either too opinionated, wanted to perform the job of my entire asset pipeline, or required extensive configuration. So I built my own!

**Comment by RyanZim** [comment]
@luckypoem It might also be of interest to you; I am planning on adding a `_draft` key so that you can mark a page as a draft in its front-matter. onessg will not compile the drafts unless you pass a cli flag (probably something like `--dev`).

**Comment by RyanZim** [comment]
Gonna close this; I do plan on making a demo repo when I get around to it, but it will not be a blog.
